<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.yourorg.mq</groupId>
  <artifactId>mq-client-util</artifactId>
  <version>1.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>mq-client-util (parent)</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>

    <spring-boot-26.version>2.6.5</spring-boot-26.version>
    <spring-boot-14.version>1.4.7.RELEASE</spring-boot-14.version>
    <mq-client-util-core.version>1.0.1-SNAPSHOT</mq-client-util-core.version>
  </properties>

  <modules>
    <module>sample-boot26-webapp</module>
    <module>sample-boot14-webapp</module>
  </modules>
</project>

